apiVersion: v1
kind: Secret
metadata:
  name: 12cdscdcs-secret
  namespace: 12cdscdcs
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
